using System.Collections.Immutable;
using System.Text;
using Domain.SourceGenerators.Authorization.Emitters;
using Domain.SourceGenerators.Authorization.Parsers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Domain.SourceGenerators.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class AuthorizationIdsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
        {
            if (!string.Equals(compilation.AssemblyName, "Domain", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            if (!PermissionTreeParser.TryParsePermissionRoots(compilation, out var permissionRoots, out var permissionErrors))
            {
                AddErrorSource(spc, "Permissions", permissionErrors);

                return;
            }

            if (!RoleIdsParser.TryParseRoles(compilation, out var roles, out var roleErrors))
            {
                AddErrorSource(spc, "Roles", roleErrors);

                return;
            }

            var permissionIdsSource = PermissionIdsEmitter.EmitPermissionIds(permissionRoots);
            spc.AddSource("PermissionIds.Generated.g.cs", permissionIdsSource);

            var roleIdsSource = RoleIdsEmitter.EmitRoleIds(roles);
            spc.AddSource("RoleIds.Generated.g.cs", roleIdsSource);
        });
    }

    private static void AddErrorSource(SourceProductionContext spc, string area, ImmutableArray<string> errors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.Append("#error Authorization code generation failed ("
                  + area
                  + "): ");

        if (errors.Length == 0)
        {
            sb.AppendLine("Unknown error.");
        }
        else
        {
            for (var i = 0; i < errors.Length; i++)
            {
                if (i != 0)
                {
                    sb.Append(" | ");
                }

                sb.Append(NormalizeError(errors[i]));
            }

            sb.AppendLine();
        }

        spc.AddSource("AuthorizationCodegen.Errors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string NormalizeError(string error)
    {
        if (string.IsNullOrWhiteSpace(error))
        {
            return "Unknown error.";
        }

        // `#error` consumes the remainder of the line; keep it single-line.
        return error.Replace("\r", " ").Replace("\n", " ").Trim();
    }
}
