version: 2
updates:

  - package-ecosystem: "nuget"
    target-branch: "master"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "cron"
      cronjob: "0 * * * *"

  - package-ecosystem: "npm"
    target-branch: "master"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "cron"
      cronjob: "0 * * * *"

  - package-ecosystem: "nuget"
    target-branch: "dev"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "cron"
      cronjob: "0 * * * *"

  - package-ecosystem: "npm"
    target-branch: "dev"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "cron"
      cronjob: "0 * * * *"
