// <auto-generated />
namespace Domain.AppEnvironment.Constants;

public static partial class AppEnvironments
{
    public static Models.AppEnvironment Development { get; } = new()
    {
        Environment = "Development",
        EnvironmentShort = "pre",
        Tag = "prerelease"
    };

    public static Models.AppEnvironment Production { get; } = new()
    {
        Environment = "Production",
        EnvironmentShort = "prod",
        Tag = "master"
    };

    public static partial Models.AppEnvironment[] AllValues => [Development, Production];
}
