// <auto-generated />
// Generated by Domain.CodeGenerator. Do not edit manually.
// Generated on 2025-11-26T17:25:23.7236008Z UTC

#nullable enable

using System;
using System.Collections.Generic;

using Domain.Authorization.Models;

namespace Domain.Authorization.Constants;

public static class PermissionIds
{
    /// <summary>
    /// Flat list of all permission paths.
    /// </summary>
    public static IReadOnlyCollection<string> All { get; } = new string[]
    {
        "_read",
        "_write",
        "api:_read",
        "api:_write",
        "api:market:_read",
        "api:market:_write",
        "api:market:assets:_read",
        "api:market:assets:_write",
        "api:market:assets:list",
        "api:market:assets:metadata",
        "api:market:assets:search",
        "api:market:orderbooks:_read",
        "api:market:orderbooks:_write",
        "api:market:orderbooks:read",
        "api:market:orderbooks:stream",
        "api:market:prices:_read",
        "api:market:prices:_write",
        "api:market:prices:historical",
        "api:market:prices:latest",
        "api:portfolio:_read",
        "api:portfolio:_write",
        "api:portfolio:accounts:_read",
        "api:portfolio:accounts:_write",
        "api:portfolio:accounts:archive",
        "api:portfolio:accounts:create",
        "api:portfolio:accounts:list",
        "api:portfolio:accounts:read",
        "api:portfolio:accounts:update",
        "api:portfolio:performance:_read",
        "api:portfolio:performance:_write",
        "api:portfolio:performance:distribution",
        "api:portfolio:performance:summary",
        "api:portfolio:performance:timeseries",
        "api:portfolio:positions:_read",
        "api:portfolio:positions:_write",
        "api:portfolio:positions:close",
        "api:portfolio:positions:list",
        "api:portfolio:positions:open",
        "api:portfolio:positions:read",
        "api:user:_read",
        "api:user:_write",
        "api:user:profile:_read",
        "api:user:profile:_write",
        "api:user:profile:avatar",
        "api:user:profile:read",
        "api:user:profile:update",
        "api:user:security:_read",
        "api:user:security:_write",
        "api:user:security:activity",
        "api:user:security:change_password",
        "api:user:security:mfa_configure",
        "api:user:security:reset_password",
    };

    /// <summary>
    /// Global permission scope identifiers covering the entire platform.
    /// </summary>
    public static class Global
    {
        /// <summary>Global read permission covering every feature.</summary>
        public const string Read = "_read";

        /// <summary>Global write permission covering every feature.</summary>
        public const string Write = "_write";
    }


    /// <summary>Permissions related to API operations.</summary>
    public static class Api
    {

        /// <summary>Read access to API operations.</summary>
        public const string ReadIdentifier = "api:_read";

        /// <summary>Write access to API operations.</summary>
        public const string WriteIdentifier = "api:_write";

        /// <summary>Market intelligence and discovery APIs.</summary>
        public static class Market
        {

            /// <summary>Read access to market APIs.</summary>
            public const string ReadIdentifier = "api:market:_read";

            /// <summary>Write access to market APIs.</summary>
            public const string WriteIdentifier = "api:market:_write";

            /// <summary>Manage the asset catalog.</summary>
            public static class Assets
            {

                /// <summary>Read access to asset catalog.</summary>
                public const string ReadIdentifier = "api:market:assets:_read";

                /// <summary>Write access to asset catalog.</summary>
                public const string WriteIdentifier = "api:market:assets:_write";

                /// <summary>List all supported assets.</summary>
                public static class List
                {
                    /// <summary>Permission path for List all supported assets.</summary>
                    public const string Identifier = "api:market:assets:list";
                }

                /// <summary>Read metadata for a specific asset.</summary>
                public static class Metadata
                {
                    /// <summary>Permission path for Read metadata for a specific asset.</summary>
                    public const string Identifier = "api:market:assets:metadata";

                    /// <summary>Template parameter 'symbol' used when materializing this permission.</summary>
                    public const string SymbolParameter = "symbol";

                    /// <summary>Creates a parameter builder for Read metadata for a specific asset.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithSymbol(string value) => new ParameterBuilder().WithSymbol(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:market:assets:metadata", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:market:assets:metadata'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithSymbol(string value)
                        {
                            return WithRaw(SymbolParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Search for assets matching filter criteria.</summary>
                public static class Search
                {
                    /// <summary>Permission path for Search for assets matching filter criteria.</summary>
                    public const string Identifier = "api:market:assets:search";
                }
            }

            /// <summary>Order book snapshot and stream data.</summary>
            public static class Orderbooks
            {

                /// <summary>Read access to order book data.</summary>
                public const string ReadIdentifier = "api:market:orderbooks:_read";

                /// <summary>Write access to order book data.</summary>
                public const string WriteIdentifier = "api:market:orderbooks:_write";

                /// <summary>Read a current order book snapshot.</summary>
                public static class Read
                {
                    /// <summary>Permission path for Read a current order book snapshot.</summary>
                    public const string Identifier = "api:market:orderbooks:read";

                    /// <summary>Template parameter 'symbol' used when materializing this permission.</summary>
                    public const string SymbolParameter = "symbol";

                    /// <summary>Creates a parameter builder for Read a current order book snapshot.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithSymbol(string value) => new ParameterBuilder().WithSymbol(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:market:orderbooks:read", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:market:orderbooks:read'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithSymbol(string value)
                        {
                            return WithRaw(SymbolParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Subscribe to incremental order book updates.</summary>
                public static class Stream
                {
                    /// <summary>Permission path for Subscribe to incremental order book updates.</summary>
                    public const string Identifier = "api:market:orderbooks:stream";

                    /// <summary>Template parameter 'symbol' used when materializing this permission.</summary>
                    public const string SymbolParameter = "symbol";

                    /// <summary>Creates a parameter builder for Subscribe to incremental order book updates.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithSymbol(string value) => new ParameterBuilder().WithSymbol(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:market:orderbooks:stream", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:market:orderbooks:stream'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithSymbol(string value)
                        {
                            return WithRaw(SymbolParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }

            /// <summary>Price discovery operations.</summary>
            public static class Prices
            {

                /// <summary>Read access to price data.</summary>
                public const string ReadIdentifier = "api:market:prices:_read";

                /// <summary>Write access to price data.</summary>
                public const string WriteIdentifier = "api:market:prices:_write";

                /// <summary>Read historical candles for an asset.</summary>
                public static class Historical
                {
                    /// <summary>Permission path for Read historical candles for an asset.</summary>
                    public const string Identifier = "api:market:prices:historical";

                    /// <summary>Template parameter 'symbol' used when materializing this permission.</summary>
                    public const string SymbolParameter = "symbol";
                    /// <summary>Template parameter 'granularity' used when materializing this permission.</summary>
                    public const string GranularityParameter = "granularity";

                    /// <summary>Creates a parameter builder for Read historical candles for an asset.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithSymbol(string value) => new ParameterBuilder().WithSymbol(value).Build();

                    public static string WithGranularity(string value) => new ParameterBuilder().WithGranularity(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:market:prices:historical", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:market:prices:historical'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithSymbol(string value)
                        {
                            return WithRaw(SymbolParameter, value);
                        }

                        public ParameterBuilder WithGranularity(string value)
                        {
                            return WithRaw(GranularityParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Read the latest price tick for an asset.</summary>
                public static class Latest
                {
                    /// <summary>Permission path for Read the latest price tick for an asset.</summary>
                    public const string Identifier = "api:market:prices:latest";

                    /// <summary>Template parameter 'symbol' used when materializing this permission.</summary>
                    public const string SymbolParameter = "symbol";

                    /// <summary>Creates a parameter builder for Read the latest price tick for an asset.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithSymbol(string value) => new ParameterBuilder().WithSymbol(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:market:prices:latest", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:market:prices:latest'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithSymbol(string value)
                        {
                            return WithRaw(SymbolParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }
        }

        /// <summary>Portfolio management operations scoped to a single user.</summary>
        public static class Portfolio
        {

            /// <summary>Read access to portfolio APIs.</summary>
            public const string ReadIdentifier = "api:portfolio:_read";

            /// <summary>Write access to portfolio APIs.</summary>
            public const string WriteIdentifier = "api:portfolio:_write";

            /// <summary>Manage trading accounts within a portfolio.</summary>
            public static class Accounts
            {

                /// <summary>Read access to portfolio accounts.</summary>
                public const string ReadIdentifier = "api:portfolio:accounts:_read";

                /// <summary>Write access to portfolio accounts.</summary>
                public const string WriteIdentifier = "api:portfolio:accounts:_write";

                /// <summary>Archive or deactivate an account.</summary>
                public static class Archive
                {
                    /// <summary>Permission path for Archive or deactivate an account.</summary>
                    public const string Identifier = "api:portfolio:accounts:archive";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'accountId' used when materializing this permission.</summary>
                    public const string AccountIdParameter = "accountId";

                    /// <summary>Creates a parameter builder for Archive or deactivate an account.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithAccountId(string value) => new ParameterBuilder().WithAccountId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:accounts:archive", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:accounts:archive'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithAccountId(string value)
                        {
                            return WithRaw(AccountIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Create a new account record.</summary>
                public static class Create
                {
                    /// <summary>Permission path for Create a new account record.</summary>
                    public const string Identifier = "api:portfolio:accounts:create";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'accountId' used when materializing this permission.</summary>
                    public const string AccountIdParameter = "accountId";

                    /// <summary>Creates a parameter builder for Create a new account record.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithAccountId(string value) => new ParameterBuilder().WithAccountId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:accounts:create", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:accounts:create'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithAccountId(string value)
                        {
                            return WithRaw(AccountIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>List all accounts for the portfolio.</summary>
                public static class List
                {
                    /// <summary>Permission path for List all accounts for the portfolio.</summary>
                    public const string Identifier = "api:portfolio:accounts:list";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'accountId' used when materializing this permission.</summary>
                    public const string AccountIdParameter = "accountId";

                    /// <summary>Creates a parameter builder for List all accounts for the portfolio.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithAccountId(string value) => new ParameterBuilder().WithAccountId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:accounts:list", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:accounts:list'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithAccountId(string value)
                        {
                            return WithRaw(AccountIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Read account details.</summary>
                public static class Read
                {
                    /// <summary>Permission path for Read account details.</summary>
                    public const string Identifier = "api:portfolio:accounts:read";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'accountId' used when materializing this permission.</summary>
                    public const string AccountIdParameter = "accountId";

                    /// <summary>Creates a parameter builder for Read account details.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithAccountId(string value) => new ParameterBuilder().WithAccountId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:accounts:read", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:accounts:read'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithAccountId(string value)
                        {
                            return WithRaw(AccountIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Update account metadata.</summary>
                public static class Update
                {
                    /// <summary>Permission path for Update account metadata.</summary>
                    public const string Identifier = "api:portfolio:accounts:update";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'accountId' used when materializing this permission.</summary>
                    public const string AccountIdParameter = "accountId";

                    /// <summary>Creates a parameter builder for Update account metadata.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithAccountId(string value) => new ParameterBuilder().WithAccountId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:accounts:update", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:accounts:update'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithAccountId(string value)
                        {
                            return WithRaw(AccountIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }

            /// <summary>Analyze portfolio performance.</summary>
            public static class Performance
            {

                /// <summary>Read access to portfolio performance.</summary>
                public const string ReadIdentifier = "api:portfolio:performance:_read";

                /// <summary>Write access to portfolio performance.</summary>
                public const string WriteIdentifier = "api:portfolio:performance:_write";

                /// <summary>Read allocation distribution data.</summary>
                public static class Distribution
                {
                    /// <summary>Permission path for Read allocation distribution data.</summary>
                    public const string Identifier = "api:portfolio:performance:distribution";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Read allocation distribution data.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:performance:distribution", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:performance:distribution'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Read aggregate performance metrics.</summary>
                public static class Summary
                {
                    /// <summary>Permission path for Read aggregate performance metrics.</summary>
                    public const string Identifier = "api:portfolio:performance:summary";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Read aggregate performance metrics.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:performance:summary", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:performance:summary'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Read performance data points over time.</summary>
                public static class Timeseries
                {
                    /// <summary>Permission path for Read performance data points over time.</summary>
                    public const string Identifier = "api:portfolio:performance:timeseries";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Read performance data points over time.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:performance:timeseries", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:performance:timeseries'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }

            /// <summary>Manage open trading positions for the portfolio.</summary>
            public static class Positions
            {

                /// <summary>Read access to portfolio positions.</summary>
                public const string ReadIdentifier = "api:portfolio:positions:_read";

                /// <summary>Write access to portfolio positions.</summary>
                public const string WriteIdentifier = "api:portfolio:positions:_write";

                /// <summary>Close an existing position.</summary>
                public static class Close
                {
                    /// <summary>Permission path for Close an existing position.</summary>
                    public const string Identifier = "api:portfolio:positions:close";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'positionId' used when materializing this permission.</summary>
                    public const string PositionIdParameter = "positionId";

                    /// <summary>Creates a parameter builder for Close an existing position.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithPositionId(string value) => new ParameterBuilder().WithPositionId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:positions:close", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:positions:close'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithPositionId(string value)
                        {
                            return WithRaw(PositionIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>List open and closed positions.</summary>
                public static class List
                {
                    /// <summary>Permission path for List open and closed positions.</summary>
                    public const string Identifier = "api:portfolio:positions:list";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'positionId' used when materializing this permission.</summary>
                    public const string PositionIdParameter = "positionId";

                    /// <summary>Creates a parameter builder for List open and closed positions.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithPositionId(string value) => new ParameterBuilder().WithPositionId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:positions:list", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:positions:list'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithPositionId(string value)
                        {
                            return WithRaw(PositionIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Open a new manual position entry.</summary>
                public static class Open
                {
                    /// <summary>Permission path for Open a new manual position entry.</summary>
                    public const string Identifier = "api:portfolio:positions:open";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'positionId' used when materializing this permission.</summary>
                    public const string PositionIdParameter = "positionId";

                    /// <summary>Creates a parameter builder for Open a new manual position entry.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithPositionId(string value) => new ParameterBuilder().WithPositionId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:positions:open", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:positions:open'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithPositionId(string value)
                        {
                            return WithRaw(PositionIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Read a specific position.</summary>
                public static class Read
                {
                    /// <summary>Permission path for Read a specific position.</summary>
                    public const string Identifier = "api:portfolio:positions:read";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";
                    /// <summary>Template parameter 'positionId' used when materializing this permission.</summary>
                    public const string PositionIdParameter = "positionId";

                    /// <summary>Creates a parameter builder for Read a specific position.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    public static string WithPositionId(string value) => new ParameterBuilder().WithPositionId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:portfolio:positions:read", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:portfolio:positions:read'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public ParameterBuilder WithPositionId(string value)
                        {
                            return WithRaw(PositionIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }
        }

        /// <summary>Manage authenticated user profile and security settings.</summary>
        public static class User
        {

            /// <summary>Read access to user APIs.</summary>
            public const string ReadIdentifier = "api:user:_read";

            /// <summary>Write access to user APIs.</summary>
            public const string WriteIdentifier = "api:user:_write";

            /// <summary>Manage user profile data.</summary>
            public static class Profile
            {

                /// <summary>Read access to profile management.</summary>
                public const string ReadIdentifier = "api:user:profile:_read";

                /// <summary>Write access to profile management.</summary>
                public const string WriteIdentifier = "api:user:profile:_write";

                /// <summary>Upload or replace the user&apos;s profile avatar.</summary>
                public static class Avatar
                {
                    /// <summary>Permission path for Upload or replace the user&apos;s profile avatar.</summary>
                    public const string Identifier = "api:user:profile:avatar";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Upload or replace the user&apos;s profile avatar.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:profile:avatar", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:profile:avatar'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Read the authenticated user&apos;s profile.</summary>
                public static class Read
                {
                    /// <summary>Permission path for Read the authenticated user&apos;s profile.</summary>
                    public const string Identifier = "api:user:profile:read";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Read the authenticated user&apos;s profile.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:profile:read", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:profile:read'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Update profile attributes such as display name.</summary>
                public static class Update
                {
                    /// <summary>Permission path for Update profile attributes such as display name.</summary>
                    public const string Identifier = "api:user:profile:update";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Update profile attributes such as display name.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:profile:update", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:profile:update'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }

            /// <summary>Manage user security credentials.</summary>
            public static class Security
            {

                /// <summary>Read access to user security.</summary>
                public const string ReadIdentifier = "api:user:security:_read";

                /// <summary>Write access to user security.</summary>
                public const string WriteIdentifier = "api:user:security:_write";

                /// <summary>Read recent security-related activity.</summary>
                public static class Activity
                {
                    /// <summary>Permission path for Read recent security-related activity.</summary>
                    public const string Identifier = "api:user:security:activity";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Read recent security-related activity.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:security:activity", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:security:activity'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Change the user&apos;s password with the current credential.</summary>
                public static class ChangePassword
                {
                    /// <summary>Permission path for Change the user&apos;s password with the current credential.</summary>
                    public const string Identifier = "api:user:security:change_password";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Change the user&apos;s password with the current credential.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:security:change_password", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:security:change_password'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Configure multi-factor authentication devices.</summary>
                public static class MfaConfigure
                {
                    /// <summary>Permission path for Configure multi-factor authentication devices.</summary>
                    public const string Identifier = "api:user:security:mfa_configure";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Configure multi-factor authentication devices.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:security:mfa_configure", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:security:mfa_configure'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }

                /// <summary>Reset a password using an out-of-band token.</summary>
                public static class ResetPassword
                {
                    /// <summary>Permission path for Reset a password using an out-of-band token.</summary>
                    public const string Identifier = "api:user:security:reset_password";

                    /// <summary>Template parameter 'userId' used when materializing this permission.</summary>
                    public const string UserIdParameter = "userId";

                    /// <summary>Creates a parameter builder for Reset a password using an out-of-band token.</summary>
                    public static ParameterBuilder CreateBuilder() => new ParameterBuilder();

                    public static string WithUserId(string value) => new ParameterBuilder().WithUserId(value).Build();

                    private static Permission PermissionDefinition => _permissionDefinition ??= ResolvePermission();
                    private static Permission? _permissionDefinition;

                    private static Permission ResolvePermission()
                    {
                        foreach (var candidate in Permissions.GetAll())
                        {
                            if (string.Equals(candidate.Path, "api:user:security:reset_password", StringComparison.Ordinal))
                            {
                                return candidate;
                            }
                        }
                        throw new InvalidOperationException("Unable to locate permission definition 'api:user:security:reset_password'.");
                    }

                    public sealed class ParameterBuilder
                    {
                        private readonly Dictionary<string, string?> _values = new Dictionary<string, string?>(StringComparer.Ordinal);

                        public ParameterBuilder WithRaw(string parameterName, string? value)
                        {
                            _values[parameterName] = value;
                            return this;
                        }

                        public ParameterBuilder WithUserId(string value)
                        {
                            return WithRaw(UserIdParameter, value);
                        }

                        public string Build()
                        {
                            if (_values.Count == 0)
                            {
                                return Identifier;
                            }

                            return PermissionDefinition.BuildPath(_values);
                        }

                        public override string ToString() => Build();
                    }
                }
            }
        }
    }
}
