// <auto-generated />
// Generated by Domain.CodeGenerator. Do not edit manually.
// Generated on 2025-11-26T16:27:31.5389494Z UTC

#nullable enable

using System;
using System.Collections.Generic;

namespace Domain.Authorization.Constants;

public static class RoleIds
{
    /// <summary>All known role codes.</summary>
    public static IReadOnlyCollection<string> AllCodes { get; } = new string[]
    {
        "ADMIN",
        "USER",
    };

    /// <summary>Identifiers and parameters for the 'Administrator' role.</summary>
    public static class Admin
    {
        /// <summary>Role code for 'Administrator'.</summary>
        public const string Code = "ADMIN";
    }

    /// <summary>Identifiers and parameters for the 'User' role.</summary>
    public static class User
    {
        /// <summary>Role code for 'User'.</summary>
        public const string Code = "USER";

        /// <summary>All template parameters consumed by this role's permission templates.</summary>
        public static IReadOnlyCollection<string> Parameters { get; } = new string[]
        {
            "roleUserId",
        };

        /// <summary>Parameter identifier 'roleUserId'.</summary>
        public const string RoleUserIdParameter = "roleUserId";
    }

}
