using System.Collections.Immutable;
using System.Text;
using Domain.SourceGenerators.Authorization.Models;
using Domain.SourceGenerators.Utilities;

namespace Domain.SourceGenerators.Authorization.Emitters;

internal static class PermissionIdsEmitter
{
    public static string EmitPermissionIds(ImmutableArray<PermissionTreeNode> roots)
    {
        var allPermissionPaths = new SortedSet<string>(StringComparer.Ordinal)
        {
            "_read",
            "_write"
        };

        var allParameters = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var root in roots)
        {
            CollectPathsAndParameters(root, parentPath: null, allPermissionPaths, allParameters);
        }

        var builder = new StringBuilder(64 * 1024);
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using Domain.Authorization.ValueObjects;");
        builder.AppendLine();
        builder.AppendLine("namespace Domain.Authorization.Constants;");
        builder.AppendLine();
        builder.AppendLine("public static class PermissionIds");
        builder.AppendLine("{");

        WriteAll(builder, allPermissionPaths);
        builder.AppendLine();
        WriteAllParameters(builder, allParameters);
        builder.AppendLine();
        WriteGlobalScopes(builder);

        foreach (var root in roots)
        {
            WritePermissionNode(
                builder,
                node: root,
                indentLevel: 1,
                inheritedParameters: ImmutableArray<string>.Empty,
                parentHasReadScope: false,
                parentHasWriteScope: false,
                parentPath: null);
        }

        builder.AppendLine("}");

        builder.AppendLine();
        WritePermissionMetadata(builder, roots);

        return builder.ToString();
    }

    private static void WritePermissionMetadata(StringBuilder builder, ImmutableArray<PermissionTreeNode> roots)
    {
        var readPaths = new SortedSet<string>(StringComparer.Ordinal) { "_read" };
        var writePaths = new SortedSet<string>(StringComparer.Ordinal) { "_write" };

        foreach (var root in roots)
        {
            CollectPathsByAccess(root, parentPath: null, readPaths, writePaths);
        }

        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Metadata about permission categories for scope evaluation.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static class PermissionMetadata");
        builder.AppendLine("{");

        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Collection of all Read permission paths.");
        builder.AppendLine("    /// These are granted by parent _read scopes.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static IReadOnlyCollection<string> RLeafPermissions { get; } = new string[]");
        builder.AppendLine("    {");
        foreach (var path in readPaths)
        {
            builder.Append("        \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(path));
            builder.AppendLine("\",");
        }
        builder.AppendLine("    };");

        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Collection of all Write permission paths.");
        builder.AppendLine("    /// These are granted by parent _write scopes.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static IReadOnlyCollection<string> WLeafPermissions { get; } = new string[]");
        builder.AppendLine("    {");
        foreach (var path in writePaths)
        {
            builder.Append("        \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(path));
            builder.AppendLine("\",");
        }
        builder.AppendLine("    };");

        builder.AppendLine("}");
    }

    private static void CollectPathsByAccess(
        PermissionTreeNode node,
        string? parentPath,
        SortedSet<string> readPaths,
        SortedSet<string> writePaths)
    {
        var currentPath = parentPath is null ? node.Identifier : parentPath + ":" + node.Identifier;

        if (node.Access == PermissionAccess.Read)
        {
            readPaths.Add(currentPath);
        }
        else if (node.Access == PermissionAccess.Write)
        {
            writePaths.Add(currentPath);
        }

        foreach (var child in node.Children)
        {
            CollectPathsByAccess(child, currentPath, readPaths, writePaths);
        }
    }

    private static void CollectPathsAndParameters(
        PermissionTreeNode node,
        string? parentPath,
        SortedSet<string> allPaths,
        SortedSet<string> allParameters)
    {
        foreach (var p in node.LocalParameters)
        {
            allParameters.Add(p);
        }

        var currentPath = parentPath is null ? node.Identifier : parentPath + ":" + node.Identifier;

        if (node.Access != PermissionAccess.Unspecified)
        {
            allPaths.Add(currentPath);
        }

        foreach (var child in node.Children)
        {
            CollectPathsAndParameters(child, currentPath, allPaths, allParameters);
        }
    }

    private static void WriteAll(StringBuilder builder, IEnumerable<string> allPaths)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Flat list of all valid permission paths.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static IReadOnlyCollection<string> All { get; } = new string[]");
        builder.AppendLine("    {");
        foreach (var path in allPaths)
        {
            builder.Append("        \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(path));
            builder.AppendLine("\",");
        }
        builder.AppendLine("    };");
    }

    private static void WriteAllParameters(StringBuilder builder, IEnumerable<string> allParameters)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Flat list of all unique parameter names used in permissions.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static IReadOnlyCollection<string> AllParameters { get; } = new string[]");
        builder.AppendLine("    {");
        foreach (var param in allParameters)
        {
            builder.Append("        \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(param));
            builder.AppendLine("\",");
        }
        builder.AppendLine("    };");
    }

    private static void WriteGlobalScopes(StringBuilder builder)
    {
        builder.AppendLine("    /// <summary>Global read scope covering every feature.</summary>");
        builder.AppendLine("    public static class Read");
        builder.AppendLine("    {");
        builder.AppendLine("        public const string Identifier = \"_read\";");
        builder.AppendLine("        private const string Path = Identifier;");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates an allow directive for global read access.</summary>");
        builder.AppendLine("        public static string Allow() => \"allow;_read\";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates a deny directive for global read access.</summary>");
        builder.AppendLine("        public static string Deny() => \"deny;_read\";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates a scope builder with the userId parameter.</summary>");
        builder.AppendLine("        public static ScopeBuilder WithUserId(string value) => new ScopeBuilder(Path, \"userId\", value);");
        builder.AppendLine();
        WriteScopeBuilderStruct(builder, indentLevel: 2, parameters: ImmutableArray.Create("userId"), useWithPrefix: false);
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>Global write scope covering every feature.</summary>");
        builder.AppendLine("    public static class Write");
        builder.AppendLine("    {");
        builder.AppendLine("        public const string Identifier = \"_write\";");
        builder.AppendLine("        private const string Path = Identifier;");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates an allow directive for global write access.</summary>");
        builder.AppendLine("        public static string Allow() => \"allow;_write\";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates a deny directive for global write access.</summary>");
        builder.AppendLine("        public static string Deny() => \"deny;_write\";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Creates a scope builder with the userId parameter.</summary>");
        builder.AppendLine("        public static ScopeBuilder WithUserId(string value) => new ScopeBuilder(Path, \"userId\", value);");
        builder.AppendLine();
        WriteScopeBuilderStruct(builder, indentLevel: 2, parameters: ImmutableArray.Create("userId"), useWithPrefix: false);
        builder.AppendLine("    }");
    }

    private static void WritePermissionNode(
        StringBuilder builder,
        PermissionTreeNode node,
        int indentLevel,
        ImmutableArray<string> inheritedParameters,
        bool parentHasReadScope,
        bool parentHasWriteScope,
        string? parentPath)
    {
        var indent = new string(' ', indentLevel * 4);

        var combinedParameters = CombineParameters(inheritedParameters, node.LocalParameters);

        var hasReadScope = node.Kind == PermissionNodeKind.Node;
        var hasWriteScope = node.Kind == PermissionNodeKind.Node;

        var className = IdentifierNaming.ToPermissionClassName(node.Identifier, parentHasReadScope, parentHasWriteScope);

        builder.AppendLine();
        builder.Append(indent);
        builder.Append("/// <summary>");
        builder.Append(SourceTextEscaping.EscapeForXmlDoc(node.Description));
        builder.AppendLine("</summary>");
        builder.Append(indent);
        builder.Append("public static class ");
        builder.AppendLine(className);
        builder.Append(indent);
        builder.AppendLine("{");

        WriteParameterConstants(builder, indentLevel + 1, combinedParameters);

        var currentPath = parentPath is null ? node.Identifier : parentPath + ":" + node.Identifier;

        if (node.Kind == PermissionNodeKind.Scope)
        {
            WriteScopeLeaf(builder, indentLevel + 1, identifier: currentPath, combinedParameters);
            builder.Append(indent);
            builder.AppendLine("}");
            return;
        }

        if (node.Kind == PermissionNodeKind.Leaf)
        {
            WritePermissionLeaf(builder, indentLevel + 1, identifier: currentPath, combinedParameters);
            builder.Append(indent);
            builder.AppendLine("}");
            return;
        }

        // Node: emit Read/Write scopes first, then children.
        var readChild = node.Children.FirstOrDefault(c => c.Kind == PermissionNodeKind.Scope && c.Access == PermissionAccess.Read);
        var writeChild = node.Children.FirstOrDefault(c => c.Kind == PermissionNodeKind.Scope && c.Access == PermissionAccess.Write);

        if (readChild is not null)
        {
            WritePermissionNode(builder, readChild, indentLevel + 1, combinedParameters, parentHasReadScope: false, parentHasWriteScope: false, parentPath: currentPath);
        }

        if (writeChild is not null)
        {
            WritePermissionNode(builder, writeChild, indentLevel + 1, combinedParameters, parentHasReadScope: false, parentHasWriteScope: false, parentPath: currentPath);
        }

        foreach (var child in node.Children)
        {
            if (child.Kind == PermissionNodeKind.Scope)
            {
                continue;
            }

            WritePermissionNode(builder, child, indentLevel + 1, combinedParameters, parentHasReadScope: true, parentHasWriteScope: true, parentPath: currentPath);
        }

        builder.Append(indent);
        builder.AppendLine("}");
    }

    private static void WriteParameterConstants(StringBuilder builder, int indentLevel, ImmutableArray<string> combinedParameters)
    {
        if (combinedParameters.Length == 0)
        {
            return;
        }

        var indent = new string(' ', indentLevel * 4);

        foreach (var parameter in combinedParameters)
        {
            var constantName = IdentifierNaming.ToParameterIdentifier(parameter) + "Parameter";
            builder.Append(indent);
            builder.Append("/// <summary>Template parameter '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(parameter));
            builder.AppendLine("' used when scoping this permission.</summary>");
            builder.Append(indent);
            builder.Append("public const string ");
            builder.Append(constantName);
            builder.Append(" = \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(parameter));
            builder.AppendLine("\";");
            builder.AppendLine();
        }
    }

    private static void WriteScopeLeaf(StringBuilder builder, int indentLevel, string identifier, ImmutableArray<string> combinedParameters)
    {
        var indent = new string(' ', indentLevel * 4);

        builder.Append(indent);
        builder.AppendLine("/// <summary>The canonical permission identifier for this scope.</summary>");
        builder.Append(indent);
        builder.Append("public const string Identifier = \"");
        builder.Append(SourceTextEscaping.EscapeForStringLiteral(identifier));
        builder.AppendLine("\";");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("private const string Path = Identifier;");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("/// <summary>Creates an allow directive for this scope.</summary>");
        builder.Append(indent);
        builder.Append("public static string Allow() => \"allow;");
        builder.Append(SourceTextEscaping.EscapeForStringLiteral(identifier));
        builder.AppendLine("\";");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("/// <summary>Creates a deny directive for this scope.</summary>");
        builder.Append(indent);
        builder.Append("public static string Deny() => \"deny;");
        builder.Append(SourceTextEscaping.EscapeForStringLiteral(identifier));
        builder.AppendLine("\";");

        if (combinedParameters.Length > 0)
        {
            builder.AppendLine();
            var first = combinedParameters[0];
            builder.Append(indent);
            builder.Append("/// <summary>Creates a scope builder with the '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(first));
            builder.AppendLine("' parameter.</summary>");
            builder.Append(indent);
            builder.Append("public static ScopeBuilder With");
            builder.Append(IdentifierNaming.ToParameterIdentifier(first));
            builder.Append("(string value) => new ScopeBuilder(Path, \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(first));
            builder.AppendLine("\", value);");
            builder.AppendLine();

            WriteScopeBuilderStruct(builder, indentLevel, combinedParameters, useWithPrefix: true);
        }
    }

    private static void WritePermissionLeaf(StringBuilder builder, int indentLevel, string identifier, ImmutableArray<string> combinedParameters)
    {
        var indent = new string(' ', indentLevel * 4);

        builder.Append(indent);
        builder.AppendLine("/// <summary>The canonical permission identifier for this permission.</summary>");
        builder.Append(indent);
        builder.Append("public const string Identifier = \"");
        builder.Append(SourceTextEscaping.EscapeForStringLiteral(identifier));
        builder.AppendLine("\";");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("private const string Path = Identifier;");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("/// <summary>Creates an allow directive for this permission.</summary>");
        builder.Append(indent);
        builder.Append("public static string Allow() => \"allow;");
        builder.Append(SourceTextEscaping.EscapeForStringLiteral(identifier));
        builder.AppendLine("\";");
        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("/// <summary>Creates a deny directive for this permission.</summary>");
        builder.Append(indent);
        builder.Append("public static string Deny() => \"deny;");
        builder.Append(SourceTextEscaping.EscapeForStringLiteral(identifier));
        builder.AppendLine("\";");

        if (combinedParameters.Length > 0)
        {
            builder.AppendLine();
            var first = combinedParameters[0];
            builder.Append(indent);
            builder.Append("/// <summary>Creates a scope builder with the '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(first));
            builder.AppendLine("' parameter.</summary>");
            builder.Append(indent);
            builder.Append("public static ScopeBuilder With");
            builder.Append(IdentifierNaming.ToParameterIdentifier(first));
            builder.Append("(string value) => new ScopeBuilder(Path, \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(first));
            builder.AppendLine("\", value);");
            builder.AppendLine();

            WriteScopeBuilderStruct(builder, indentLevel, combinedParameters, useWithPrefix: true);
        }

        builder.AppendLine();
        builder.Append(indent);
        builder.AppendLine("/// <summary>Creates a permission request builder for HasPermission calls.</summary>");
        builder.Append(indent);
        builder.AppendLine("public static PermissionRequestBuilder Permission => new PermissionRequestBuilder(Path);");
        builder.AppendLine();
        WritePermissionRequestBuilderStruct(builder, indentLevel, combinedParameters);
    }

    private static void WriteScopeBuilderStruct(StringBuilder builder, int indentLevel, ImmutableArray<string> parameters, bool useWithPrefix)
    {
        var indent = new string(' ', indentLevel * 4);
        var memberIndent = new string(' ', (indentLevel + 1) * 4);

        builder.Append(indent);
        builder.AppendLine("/// <summary>Immutable builder for constructing scoped directives with parameters.</summary>");
        builder.Append(indent);
        builder.AppendLine("public readonly struct ScopeBuilder");
        builder.Append(indent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("private readonly string _path;");
        builder.Append(memberIndent);
        builder.AppendLine("private readonly string _params;");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("internal ScopeBuilder(string path, string key, string value)");
        builder.Append(memberIndent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("    _path = path;");
        builder.Append(memberIndent);
        builder.AppendLine("    _params = $\"{key}={value}\";");
        builder.Append(memberIndent);
        builder.AppendLine("}");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("private ScopeBuilder(string path, string existingParams, string key, string value)");
        builder.Append(memberIndent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("    _path = path;");
        builder.Append(memberIndent);
        builder.AppendLine("    _params = $\"{existingParams};{key}={value}\";");
        builder.Append(memberIndent);
        builder.AppendLine("}");
        builder.AppendLine();

        foreach (var parameter in parameters)
        {
            var paramId = IdentifierNaming.ToParameterIdentifier(parameter);
            var methodName = useWithPrefix ? "With" + paramId : paramId;

            builder.Append(memberIndent);
            builder.Append("/// <summary>Adds the '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(parameter));
            builder.AppendLine("' parameter to this builder.</summary>");
            builder.Append(memberIndent);
            builder.Append("public ScopeBuilder ");
            builder.Append(methodName);
            builder.Append("(string value) =>\n");
            builder.Append(memberIndent);
            builder.Append("    new ScopeBuilder(_path, _params, \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(parameter));
            builder.AppendLine("\", value);");
            builder.AppendLine();
        }

        builder.Append(memberIndent);
        builder.AppendLine("/// <summary>Creates an allow directive with the configured parameters.</summary>");
        builder.Append(memberIndent);
        builder.AppendLine("public string Allow() => string.IsNullOrEmpty(_params)");
        builder.Append(memberIndent);
        builder.AppendLine("    ? $\"allow;{_path}\"");
        builder.Append(memberIndent);
        builder.AppendLine("    : $\"allow;{_path};{_params}\";");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("/// <summary>Creates a deny directive with the configured parameters.</summary>");
        builder.Append(memberIndent);
        builder.AppendLine("public string Deny() => string.IsNullOrEmpty(_params)");
        builder.Append(memberIndent);
        builder.AppendLine("    ? $\"deny;{_path}\"");
        builder.Append(memberIndent);
        builder.AppendLine("    : $\"deny;{_path};{_params}\";");

        builder.Append(indent);
        builder.AppendLine("}");
    }

    private static void WritePermissionRequestBuilderStruct(StringBuilder builder, int indentLevel, ImmutableArray<string> parameters)
    {
        var indent = new string(' ', indentLevel * 4);
        var memberIndent = new string(' ', (indentLevel + 1) * 4);

        builder.Append(indent);
        builder.AppendLine("/// <summary>Immutable builder for constructing permission requests with parameters.</summary>");
        builder.Append(indent);
        builder.AppendLine("public readonly struct PermissionRequestBuilder");
        builder.Append(indent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("private readonly string _path;");
        builder.Append(memberIndent);
        builder.AppendLine("private readonly string? _params;");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("internal PermissionRequestBuilder(string path)");
        builder.Append(memberIndent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("    _path = path;");
        builder.Append(memberIndent);
        builder.AppendLine("    _params = null;");
        builder.Append(memberIndent);
        builder.AppendLine("}");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("private PermissionRequestBuilder(string path, string key, string value)");
        builder.Append(memberIndent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("    _path = path;");
        builder.Append(memberIndent);
        builder.AppendLine("    _params = $\"{key}={value}\";");
        builder.Append(memberIndent);
        builder.AppendLine("}");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("private PermissionRequestBuilder(string path, string existingParams, string key, string value)");
        builder.Append(memberIndent);
        builder.AppendLine("{");
        builder.Append(memberIndent);
        builder.AppendLine("    _path = path;");
        builder.Append(memberIndent);
        builder.AppendLine("    _params = $\"{existingParams};{key}={value}\";");
        builder.Append(memberIndent);
        builder.AppendLine("}");
        builder.AppendLine();

        foreach (var parameter in parameters)
        {
            var paramId = IdentifierNaming.ToParameterIdentifier(parameter);

            builder.Append(memberIndent);
            builder.Append("/// <summary>Adds the '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(parameter));
            builder.AppendLine("' parameter to this permission request.</summary>");
            builder.Append(memberIndent);
            builder.Append("public PermissionRequestBuilder With");
            builder.Append(paramId);
            builder.Append("(string value) =>\n");
            builder.Append(memberIndent);
            builder.AppendLine("    string.IsNullOrEmpty(_params)");
            builder.Append(memberIndent);
            builder.Append("        ? new PermissionRequestBuilder(_path, \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(parameter));
            builder.AppendLine("\", value)");
            builder.Append(memberIndent);
            builder.Append("        : new PermissionRequestBuilder(_path, _params, \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(parameter));
            builder.AppendLine("\", value);");
            builder.AppendLine();
        }

        builder.Append(memberIndent);
        builder.AppendLine("/// <summary>Converts this builder to its string representation for HasPermission calls.</summary>");
        builder.Append(memberIndent);
        builder.AppendLine("public override string ToString() =>");
        builder.Append(memberIndent);
        builder.AppendLine("    string.IsNullOrEmpty(_params) ? _path : $\"{_path};{_params}\";");
        builder.AppendLine();

        builder.Append(memberIndent);
        builder.AppendLine("/// <summary>Implicit conversion to string for seamless use with HasPermission methods.</summary>");
        builder.Append(memberIndent);
        builder.AppendLine("public static implicit operator string(PermissionRequestBuilder builder) => builder.ToString();");

        builder.Append(indent);
        builder.AppendLine("}");
    }

    private static ImmutableArray<string> CombineParameters(ImmutableArray<string> inherited, ImmutableArray<string> local)
    {
        if (inherited.Length == 0 && local.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var set = new HashSet<string>(StringComparer.Ordinal);
        var builder = ImmutableArray.CreateBuilder<string>();

        foreach (var p in inherited)
        {
            if (set.Add(p))
            {
                builder.Add(p);
            }
        }

        foreach (var p in local)
        {
            if (set.Add(p))
            {
                builder.Add(p);
            }
        }

        return builder.ToImmutable();
    }
}
