using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Domain.SourceGenerators.Authorization.Models;
using Domain.SourceGenerators.Utilities;

namespace Domain.SourceGenerators.Authorization.Emitters;

internal static class RoleIdsEmitter
{
    public static string EmitRoleIds(ImmutableArray<RoleDefinitionInfo> roles)
    {
        var sorted = roles
            .OrderBy(static r => r.Code, StringComparer.Ordinal)
            .ToList();

        var builder = new StringBuilder(8 * 1024);
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine("namespace Domain.Authorization.Constants;");
        builder.AppendLine();
        builder.AppendLine("public static class RoleIds");
        builder.AppendLine("{");

        builder.AppendLine("    /// <summary>All known role codes.</summary>");
        builder.AppendLine("    public static IReadOnlyCollection<string> AllCodes { get; } = new string[]");
        builder.AppendLine("    {");
        foreach (var role in sorted)
        {
            builder.Append("        \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(role.Code));
            builder.AppendLine("\",");
        }
        builder.AppendLine("    };");

        foreach (var role in sorted)
        {
            var className = IdentifierNaming.ToRoleClassName(role.Code);

            builder.AppendLine();
            builder.Append("    /// <summary>Identifiers and parameters for the '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(role.Name));
            builder.AppendLine("' role.</summary>");
            builder.Append("    public static class ");
            builder.AppendLine(className);
            builder.AppendLine("    {");
            builder.Append("        /// <summary>Role code for '");
            builder.Append(SourceTextEscaping.EscapeForXmlDoc(role.Name));
            builder.AppendLine("'.</summary>");
            builder.Append("        public const string Code = \"");
            builder.Append(SourceTextEscaping.EscapeForStringLiteral(role.Code));
            builder.AppendLine("\";");

            if (role.TemplateParameters.Length > 0)
            {
                builder.AppendLine();
                builder.AppendLine("        /// <summary>All template parameters consumed by this role's permission templates.</summary>");
                builder.AppendLine("        public static IReadOnlyCollection<string> Parameters { get; } = new string[]");
                builder.AppendLine("        {");
                foreach (var param in role.TemplateParameters)
                {
                    builder.Append("            \"");
                    builder.Append(SourceTextEscaping.EscapeForStringLiteral(param));
                    builder.AppendLine("\",");
                }
                builder.AppendLine("        };");

                foreach (var param in role.TemplateParameters)
                {
                    builder.AppendLine();
                    builder.Append("        /// <summary>Parameter identifier '");
                    builder.Append(SourceTextEscaping.EscapeForXmlDoc(param));
                    builder.AppendLine("'.</summary>");
                    builder.Append("        public const string ");
                    builder.Append(IdentifierNaming.ToParameterIdentifier(param));
                    builder.Append("Parameter = \"");
                    builder.Append(SourceTextEscaping.EscapeForStringLiteral(param));
                    builder.AppendLine("\";");
                }
            }

            builder.AppendLine("    }");
        }

        builder.AppendLine();
        builder.AppendLine("}");

        return builder.ToString();
    }
}
