using System;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Domain.CodeGenerator.Generators;

sealed class BuildConstantsGenerator : ICodeGenerationTask
{
    internal const string TaskId = "BuildConstants";

    public string Id => TaskId;

    public string GetDefaultOutputPath(string applicationBaseDirectory) =>
        Path.Combine(applicationBaseDirectory, "GeneratedBuildConstants.cs");

    public async Task GenerateAsync(CodeGenerationContext context, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(context.Options);

        cancellationToken.ThrowIfCancellationRequested();

        var options = context.Options;
        var outputPath = context.GetOutputPath(Id);
        var directory = Path.GetDirectoryName(outputPath);

        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by Domain.CodeGenerator. Do not edit manually.");
        builder.AppendLine($"// Generated on {context.UtcNow:O} UTC");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Build");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Contains application build constants.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    internal static class Constants");
        builder.AppendLine("    {");
        AppendConstant(builder, "AppName", options.AppName, "The application name.");
        builder.AppendLine();
        AppendConstant(builder, "AppTitle", options.AppTitle, "The application title.");
        builder.AppendLine();
        AppendConstant(builder, "AppDescription", options.AppDescription, "The application description.");
        builder.AppendLine();
        AppendConstant(builder, "Version", options.Version, "The application version.");
        builder.AppendLine();
        AppendConstant(builder, "AppTag", options.AppTag, "The application AppTag.");
        builder.AppendLine();
        AppendConstant(builder, "BuildPayload", options.BuildPayload, "The application build payload.");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc/>");
        builder.AppendLine("    internal class ApplicationConstants : global::Application.Abstractions.Application.IApplicationConstants");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public static global::Application.Abstractions.Application.IApplicationConstants Instance { get; } = new global::Build.ApplicationConstants();");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public string AppName { get; } = global::Build.Constants.AppName;");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public string AppTitle { get; } = global::Build.Constants.AppTitle;");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public string AppDescription { get; } = global::Build.Constants.AppDescription;");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public string Version { get; } = global::Build.Constants.Version;");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public string AppTag { get; } = global::Build.Constants.AppTag;");
        builder.AppendLine();
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public string BuildPayload { get; } = global::Build.Constants.BuildPayload;");
        builder.AppendLine("    }");
        builder.AppendLine();

        // Generate BaseCommand<T> class
        var baseCommandType = string.IsNullOrWhiteSpace(options.BaseCommandType)
            ? "global::Application.Abstractions.Application.BaseCommand"
            : $"global::{options.BaseCommandType}";

        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Base command class with application constants support.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <typeparam name=\"THostApplicationBuilder\">The type of host application builder.</typeparam>");
        builder.AppendLine($"    internal abstract class BaseCommand<[global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All)] THostApplicationBuilder> : {baseCommandType}<THostApplicationBuilder>");
        builder.AppendLine("        where THostApplicationBuilder : global::Microsoft.Extensions.Hosting.IHostApplicationBuilder");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <inheritdoc/>");
        builder.AppendLine("        public override global::Application.Abstractions.Application.IApplicationConstants ApplicationConstants { get; } = global::Build.ApplicationConstants.Instance;");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        var contents = builder.ToString();

        if (File.Exists(outputPath))
        {
            var existing = await File.ReadAllTextAsync(outputPath, cancellationToken);
            if (string.Equals(existing, contents, StringComparison.Ordinal))
            {
                return;
            }
        }

        var encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
        await File.WriteAllTextAsync(outputPath, contents, encoding, cancellationToken);
    }

    private static void AppendConstant(StringBuilder builder, string name, string value, string documentation)
    {
        builder.AppendLine("        /// <summary>");
        builder.Append("        /// ");
        builder.AppendLine(documentation);
        builder.AppendLine("        /// </summary>");
        builder.Append("        public const string ");
        builder.Append(name);
        builder.Append(" = ");
        builder.Append(ToLiteral(value));
        builder.AppendLine(";");
    }

    private static string ToLiteral(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');

        foreach (var character in value)
        {
            builder.Append(character switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\0' => "\\0",
                '\a' => "\\a",
                '\b' => "\\b",
                '\f' => "\\f",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\v' => "\\v",
                _ when char.IsControl(character) => FormatControlCharacter(character),
                _ => character.ToString(CultureInfo.InvariantCulture),
            });
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string FormatControlCharacter(char character)
    {
        return string.Format(CultureInfo.InvariantCulture, "\\u{0:x4}", (int)character);
    }
}
